<a href="https://colab.research.google.com/github/191919201921/Zadania_Domowe_ADS/blob/main/Kopia_notatnika_M3MORE_NUMPY_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Praktyczne zadania - Podstawy Numpy w Python**

# Zadanie 1


1. Do zmiennych x,y przypisz dwie dowolne, różne liczby. 

2. Wyświetl je.

3. Zamień je wartościami i wyświetl rezultat po zamianie.

In [ ]:
import numpy as np

x,y = 1,2
x

1

In [ ]:
x,y = y,x
x

1

## Podpowiedzi


In [ ]:
# Python przyjmuje szereg zmiennych po przecinku. Przykład: x,y,z = funkcja(a,b), 
# przy założeniu, że funkcja zwraca 3 wartości, będą one przypisane kolejno do zmiennych x, y, z.
# W tym przypadku do zamiany wartości można wykorzystać zapis x,y = y,x

## Podpowiedzi + rozwiązanie

In [ ]:
x = 24
y = 20
print("x:", x, "y:", y)

# Python przyjmuje szereg zmiennych po przecinku. Przykład: x,y,z = funkcja(a,b), 
# przy założeniu, że funkcja zwraca 3 wartości, będą one przypisane kolejno do zmiennych x, y, z.
# W tym przypadku do zamiany wartości można wykorzystać zapis x,y = y,x

x, y = y, x
print("x:", x, "y:", y)

x: 24 y: 20
x: 20 y: 24


#Zadanie 2

1. Stwórz zmienną typu string o wartości "12345".

2. Wyświetl pierwszy i ostatni element.

3. Wyświetl długość elementu.

4. Wyświetl typ zmiennej.

5. Zmień typ zmiennej na integer.

6. Wyświetl typ zmiennej po zmianie typu.

In [ ]:
zmienna = '12345'
print(zmienna[0])
print(zmienna[-1])
print(len(zmienna))
print(type(zmienna))


1
5
5
<class 'str'>


In [ ]:
zmienna = int(zmienna)
type(zmienna)

int

##Podpowiedzi

In [ ]:
# Stringi w Python można adresować również od końca. Wtedy należy wykorzystać zapis string[-1], który zwraca ostatni znak.
# Typ zmiennej można wyświetlić za pomocą funkcji type(zmienna)

##Podpowiedzi + rozwiązanie

In [ ]:
# Stringi w Python można adresować również od końca. Wtedy należy wykorzystać zapis string[-1], który zwraca ostatni znak.
# Typ zmiennej można wyświetlić za pomocą funkcji type(zmienna)

numbers = "12345"
print("Pierwszy element:",numbers[0], "\nOstatni element:", numbers[-1])
print("Długość:", len(numbers))
print("Typ: ", type(numbers))

numbers = int(numbers)
print("Typ po zmianie: ", type(numbers))

Pierwszy element: 1 
Ostatni element: 5
Długość: 5
Typ:  <class 'str'>
Typ po zmianie:  <class 'int'>


#Zadanie 3

1. Stwórz funkcję **znajdz_sume** przyjmującą 2 parametry - **a** i **b**, i zwracającą ich sumę.

2. Niech **a** ma domyślną wartość **5**, a **b** domyślną wartość **2**.

3. Wywołaj funkcję bez podawania żadnych parametrów. Jaki będzie wynik?

4. Wywołaj funkcję podając jej 2 parametry : a=9, b= 3.

5. Wywołaj funkcję podając tylko jeden z argumentów. Przykładowo: **znajdz_sume(3)**

6. Zaobserwuj jak funkcja reaguje na różne sposoby podawania parametrów.


In [ ]:
def znajdz_sume(a=5,b=2):
  return a+b
  

In [ ]:
znajdz_sume()

7

In [ ]:
znajdz_sume(9,3)

12

In [ ]:
znajdz_sume(b=4)

9

##Podpowiedzi

In [ ]:
# Domyślny parametr funkcji można zadeklarować w momencie jej definiowania, 
# przy wykorzystaniu przykładowego zapisu def funkcja(a=2, b=True, c="color")

##Podpowiedzi + rozwiązanie

In [ ]:
# Domyślny parametr funkcji można zadeklarować w momencie jej definiowania, 
# przy wykorzystaniu przykładowego zapisu def funkcja(a=2, b=True, c="color")

def znajdz_sume(a=5, b=2):
    return a + b

print(znajdz_sume())
print(znajdz_sume(9,3))
print(znajdz_sume(3))

7
12
5


#Zadanie 4

Stwórz anonimową funkcję **lambda**, która zwraca odwrócony string podany przez użytkownika.

In [ ]:
xlambda = lambda x: x[::-1]
print(xlambda(input("podaj string: ")))

podaj string: kacper
repcak


##Podpowiedzi

In [ ]:
# Funkcje anonimowe (typu lambda) tworzy się na przykład wewnątrz definicji zmiennej. 
# Nie jest to zalecany przez literaturę sposób programowania (kod jest mniej czytelny), niemniej tego typu funkcje można spotkać.
# Definiuje się je za pomocą zapisu : zmienna = lambda x: x*3
# Powyższy zapis przypisze do obiektu "zmienna" wartość równą x razy 3.
# Spróbuj wykorzystać ten zapis funkcji aby odwrócić string.

##Podpowiedzi + rozwiązanie

In [ ]:
# Funkcje anonimowe (typu lambda) tworzy się na przykład wewnątrz definicji zmiennej. 
# Nie jest to zalecany przez literaturę sposób programowania (kod jest mniej czytelny), niemniej tego typu funkcje można spotkać.
# Definiuje się je za pomocą zapisu : zmienna = lambda x: x*3
# Powyższy zapis przypisze do obiektu "zmienna" wartość równą x razy 3.
# Spróbuj wykorzystać ten zapis funkcji aby odwrócić string.

palindrom = lambda v: v[::-1]
print(palindrom(input("Podaj string do odwrócenia: ")))

Podaj string do odwrócenia: nice
ecin


#Zadanie 5

1. Zaimportuj numpy jako np.

2. Stwórz array z 25 liczb pomiędzy 1 a 100 (włącznie z 100) i zapisz jako zmienna **ar1**.

3. Wyświetl typ zmiennej **ar1** oraz typ danych przez nią przechowywanych.

In [ ]:
np.linspace(1,100,num=25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [ ]:
ar = np.linspace(1,100,num=25)
type(ar)

numpy.ndarray

In [ ]:
ar.dtype

dtype('float64')

##Podpowiedzi


In [ ]:
# Zwyczajowy zapis importu biblioteki numpy to: import numpy as np
# Do stworzenia array wykorzystaj funkcję np.linspace(a,b,c), gdzie a to wartość początkowa, b to wartość końcowa a c to ilość liczb w array.
# Do wyświetlenia typu danych zawartych wewnątrz array/tabeli itp. wykorzystaj zapis zmienna.dtype . 
# Warto zapamiętać rozróżnienie pomiędzy typem zmiennej a typem danych - w przyszłości będziesz tego dużo używać.
# Funkcja np.linspace tworzy liniowy rozkład pomiędzy wartościami parametru "od" (większe lub równe) oraz "do"(mniejsze lub równe), następnie zapisuje żadaną ilość liczb w równych odstępach.

##Podpowiedzi + rozwiązanie


In [ ]:
# Zwyczajowy zapis importu biblioteki numpy to: import numpy as np
# Do stworzenia array wykorzystaj funkcję np.linspace(a,b,c), gdzie a to wartość początkowa, b to wartość końcowa a c to ilość liczb w array.
# Do wyświetlenia typu danych zawartych wewnątrz array/tabeli itp. wykorzystaj zapis zmienna.dtype . 
# Warto zapamiętać rozróżnienie pomiędzy typem zmiennej a typem danych - w przyszłości będziesz tego dużo używać.
# Funkcja np.linspace tworzy liniowy rozkład pomiędzy wartościami parametru "od" (większe lub równe) oraz "do"(mniejsze lub równe), następnie zapisuje żadaną ilość liczb w równych odstępach.

import numpy as np
ar1= np.linspace(1,100,25)

print(ar1)
print("Typ zmiennej ar1: ", type(ar1))
print("Typ zmiennych wewnątrz ar1: ", ar1.dtype)

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]
Typ zmiennej ar1:  <class 'numpy.ndarray'>
Typ zmiennych wewnątrz ar1:  float64


#Zadanie 6


1. Zaimportuj numpy jako np.

2. Stwórz array 20 liczb od 30 do 50 (z wyłączeniem 50) za pomocą funkcji **np.arange**

3. Zapisz go jako zmienna **ar2**.

4. Porównaj różnice w działaniu funkcji **linspace** i **arange**.

In [ ]:
ar2 = np.arange(30,50)
ar2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

##Podpowiedzi

In [ ]:
# Funkcja np.arange tworzy array liczb całkowitych od-do, 
# na zasadzie większe lub równe parametru "od", mniejsze od parametru "do"

##Podpowiedzi + rozwiązanie

In [ ]:
# Funkcja np.arange tworzy array liczb całkowitych od-do, 
# na zasadzie większe lub równe parametru "od", mniejsze od parametru "do"

ar2 = np.arange(30,50)
print(ar2)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#Zadanie 7

Stwórz i wyświetl trzy array:

1. Array wszystkich parzystych liczb od 20 do 68, za wyjątkiem 68.
2. Array wszystkich liczb od 0 do 100 (włącznie), z rozmiarem kroku 20.
3. Array 14 liczb od -7 do 7 z równymi odstępami.

In [ ]:
ar3 = np.arange(20,68,2)
ar3

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66])

In [ ]:
ar4 = np.arange(0,101,20)
ar4

array([  0,  20,  40,  60,  80, 100])

In [ ]:
ar5 = np.linspace(-7,7,14)
ar5

array([-7.        , -5.92307692, -4.84615385, -3.76923077, -2.69230769,
       -1.61538462, -0.53846154,  0.53846154,  1.61538462,  2.69230769,
        3.76923077,  4.84615385,  5.92307692,  7.        ])

##Podpowiedzi

In [ ]:
# Do tworzenia array z określonym krokiem wykorzystaj funkcję np.arange
# Do tworzenia array z określoną liczbą wpisów wykorzystaj funkcję np.linspace
# Zwróć uwagę na interpretację parametrów przez te funkcje - jedna traktuje podane wartości jako od-do na zasadzie większe lub równe, mniejsze lub równe a druga większe lub równe i mniejsze

##Podpowiedzi + rozwiązanie

In [ ]:
# Do tworzenia array z określonym krokiem wykorzystaj funkcję np.arange
# Do tworzenia array z określoną liczbą wpisów wykorzystaj funkcję np.linspace
# Zwróć uwagę na interpretację parametrów przez te funkcje - jedna traktuje podane wartości jako od-do na zasadzie większe lub równe, mniejsze lub równe a druga większe lub równe i mniejsze

a = np.arange(20,68,2)
b = np.arange(0,101,20)
c = np.linspace(-7,7,14)

print(a)
print(b)
print(c)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66]
[  0  20  40  60  80 100]
[-7.         -5.92307692 -4.84615385 -3.76923077 -2.69230769 -1.61538462
 -0.53846154  0.53846154  1.61538462  2.69230769  3.76923077  4.84615385
  5.92307692  7.        ]


#Zadanie 8

1. Stwórz array z 10 liczb od 0 do 20 i przypisz go do zmiennej **ar3**.<br>
2. Użyj funkcji **np.linspace**<br>
3. Znajdź max, min i sumę array.

In [ ]:
ar6 = np.linspace(0,20,10)

In [ ]:
print(ar6)
print(ar6.max())
print(ar6.min())
print(ar6.sum())

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
20.0
0.0
100.0


##Podpowiedzi

In [ ]:
# Do znajdywania wartości minimalnych i maksymalnych w array wykorzystaj funkcje np.amin() oraz np.amax()
# Sumę array możesz łatwo policzyć wykorzystując funkcję np.sum()

##Podpowiedzi + rozwiązanie

In [ ]:
# Do znajdywania wartości minimalnych i maksymalnych w array wykorzystaj funkcje np.amin() oraz np.amax()
# Sumę array możesz łatwo policzyć wykorzystując funkcję np.sum()

ar3 = np.linspace(0,20,10)
print(ar3)
print(np.amin(ar3))
print(np.amax(ar3))
print(np.sum(ar3))

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
0.0
20.0
100.0


#Zadanie 9

1. Stwórz dwa array o wielkości 4, z numerami 2,3,4,5 w **array1** oraz 6,8,10,12 w **array2**.

2. Znajdź sumę, iloczyn, różnicę oraz iloraz.

3. Wyświetl wyniki.

In [ ]:
ar7 = np.arange(2,6,1)
ar8 = np.arange(6,13,2)
print(ar7)
print(ar8)

[2 3 4 5]
[ 6  8 10 12]


In [ ]:
ar7 + ar8

array([ 8, 11, 14, 17])

In [ ]:
ar7*ar8

array([12, 24, 40, 60])

In [ ]:
ar7-ar8

array([-4, -5, -6, -7])

In [ ]:
ar7/ar8

array([0.33333333, 0.375     , 0.4       , 0.41666667])

In [ ]:
ar9 = np.array([2,3,4,5,6])
ar7/ar9

ValueError: ignored

##Podpowiedzi

In [ ]:
# Array "ręcznie" można definiować za pomocą zapisu array1 = np.array([2,3,4,5])
# Działania matematyczne na array można przeprowadzać, jak na normalnych zmiennych.
# Zaobserwuj co się stanie, jak arrays będą miały różne wielkości (długości).

##Podpowiedzi + rozwiązanie

In [ ]:
# Array "ręcznie" można definiować za pomocą zapisu array1 = np.array([2,3,4,5])
# Działania matematyczne na array można przeprowadzać, jak na normalnych zmiennych.
# Zaobserwuj co się stanie, jak arrays będą miały różne wielkości (długości).

array1 = np.array([2, 3, 4, 5])
array2 = np.array([6, 8, 10, 12])

array_sum = array1 + array2
print("Suma: ", array_sum)
product = array1 * array2
print("Iloczyn: ",product)
difference = array1 - array2
print("Różnica: ", difference)
quotient = array1 / array2
print("Iloraz: ", quotient)

Suma:  [ 8 11 14 17]
Iloczyn:  [12 24 40 60]
Różnica:  [-4 -5 -6 -7]
Iloraz:  [0.33333333 0.375      0.4        0.41666667]


#Zadanie 10

1. Stwórz manualnie array z wartościami [ -5, -69, -26, 5, 12, 99].

2. Na jego podstawie stwórz array o nazwie **abs_values** zawierający wartości bezwzględne z powyższego array.

3. Wyświetl wszystkie wartości w array **abs_values** będące większe lub równe 26.



In [ ]:
ar10 = np.array([-5, -69, -26, 5, 12, 99])

In [ ]:
ar11 = abs(ar10)
ar11

array([ 5, 69, 26,  5, 12, 99])

In [ ]:
ar11[ar11>=26]

array([69, 26, 99])

##Podpowiedzi

In [ ]:
# Aby znaleźć wartości bezwzględne wykorzystaj funkcję abs().
# Najskuteczniejszą metodą filtrowania danych (najszybszą pod względem czasu obliczeń) jest filtrowanie dataframe 
# lub array przez ich własną instancję z zadanym warunkiem logicznym.
# Przykładowe zadanie: wyświetl elementy array ar3 mniejsze od 12. 
# Zapis ar3[ar3<12], który z Pythona na nasze oznacza mniej więcej: weź całość ar3 (część zapisu poza []), 
# ale tylko te elementy ar3, które są mniejsze od 12 (wewnątrz []).
# Będziesz tego typu zapisów używać bardzo dużo - i dla danych typu array i pandas dataframe. 

##Podpowiedzi + rozwiązanie

In [ ]:
# Aby znaleźć wartości bezwzględne wykorzystaj funkcję abs().
# Najskuteczniejszą metodą filtrowania danych (najszybszą pod względem czasu obliczeń) jest filtrowanie dataframe 
# lub array przez ich własną instancję z zadanym warunkiem logicznym.
# Przykładowe zadanie: wyświetl elementy array ar3 mniejsze od 12. 
# Zapis ar3[ar3<12], który z Pythona na nasze oznacza mniej więcej: weź całość ar3 (część zapisu poza []), 
# ale tylko te elementy ar3, które są mniejsze od 12 (wewnątrz []).
# Będziesz tego typu zapisów używać bardzo dużo - i dla danych typu array i pandas dataframe. 

abs_values = abs(np.array( [-5, -69, -26, 5, 12, 99] ))
print(abs_values[abs_values >= 26])

[69 26 99]


#Zadanie 11

1. Stwórz macierz z 3 wierszami i przypisz ją do zmiennej **mat1**.

> [1,2,3]<br>
> [4,5,6]<br>
> [7,8,9]<br>

2. Wyświetl kształt macierzy.

In [ ]:
matrix = np.matrix('1,2,3;3,5,6;7,8,9')
matrix

matrix([[1, 2, 3],
        [3, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix.shape

(3, 3)

##Podpowiedzi

In [ ]:
# Według interpretacji numpy, macierz to nic innego jak zbiór równych wierszy będących listami lub arrays.
# Można ją zdefiniować za pomocą funkcji np.array(), podając po przecinku pożądane wiersze jako arrays lub listy.
# Kształt macierzy lub tablicy można poznać za pomocą mat1.shape

##Podpowiedzi + rozwiązanie

In [ ]:
# Według interpretacji numpy, macierz to nic innego jak zbiór równych wierszy będących listami lub arrays.
# Można ją zdefiniować za pomocą funkcji np.array(), podając po przecinku pożądane wiersze jako arrays lub listy.
# Kształt macierzy lub tablicy można poznać za pomocą mat1.shape

mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat1)
print("Kształt macierzy: ", mat1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Kształt macierzy:  (3, 3)


#Zadanie 12

1. Przefiltruj oraz wyświetl elementy **mat1** większe od 5.

2. Użyj sposobu filtrowania z zadania 10.

3. Wartościom mniejszym lub równym 5 przypisz wartość 0.

4. Wyświetl wynik.

In [ ]:
matrix[matrix>5]

matrix([[6, 7, 8, 9]])

In [ ]:
matrix[matrix<=5] = 0
matrix

matrix([[0, 0, 0],
        [0, 0, 6],
        [7, 8, 9]])

##Podpowiedzi

In [ ]:
# Filtrowanie zbiorów danych przez nie same, ale z warunkiem logicznym można wykorzystać również do zmiany wartości wewnątrz zbiorów danych.
# Przykładowo - zapis mat1[mat1 > 3] = 66 oznacza: weź zbiór mat1 i wszystkim jego elementom większym od 3 przypisz wartość 66.
# W miejsce przypisania wartości (tu 66) można też stosować na przykład funkcje.

##Podpowiedzi + rozwiązanie

In [ ]:
# Filtrowanie zbiorów danych przez nie same, ale z warunkiem logicznym można wykorzystać również do zmiany wartości wewnątrz zbiorów danych.
# Przykładowo - zapis mat1[mat1 > 3] = 66 oznacza: weź zbiór mat1 i wszystkim jego elementom większym od 3 przypisz wartość 66.
# W miejsce przypisania wartości (tu 66) można też stosować na przykład funkcje.

print(mat1[mat1 > 5])
mat1[mat1 <= 5] = 0
print(mat1)

[6 7 8 9]
[[0 0 0]
 [0 0 6]
 [7 8 9]]


#Zadanie 13

1. Stwórz np.array składający się z 16 liczb od 20 do 35 włącznie, i opisz go zmienną **ar4**. Użyj funkcji **linspace**.

2. Przekształć **ar4** w macierzy o kształcie (4,4) i wyświetl ją.

3. Przekształć **ar4** w macierz o 8 kolumnach i zmuś Python do domyślenia się (policzenia), ile wierszy potrzeba. Wyświetl wynik.

4. Przekształć **ar4** w macierz o 8 wierszach i zmuś Python do domyślenia się (policzenia), ile kolumn potrzeba. Wyświetl wynik.

5. Zobacz co się stanie, jeśli zmusisz Python do przekształcenia macierzy np w rozmiar (4,5) - tj. niemożliwe będzie zapełnienie go 16 elementami zawartymi w **ar4**.


In [ ]:
ar11 = np.linspace(20,35,16)
ar11

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35.])

In [ ]:
ar11.reshape(4,4)

array([[20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.],
       [32., 33., 34., 35.]])

In [ ]:
ar11.reshape(8,-1)

array([[20., 21.],
       [22., 23.],
       [24., 25.],
       [26., 27.],
       [28., 29.],
       [30., 31.],
       [32., 33.],
       [34., 35.]])

In [ ]:
ar11.reshape(-1,8)

array([[20., 21., 22., 23., 24., 25., 26., 27.],
       [28., 29., 30., 31., 32., 33., 34., 35.]])

In [ ]:
ar11.reshape(4,5)

ValueError: ignored

##Podpowiedzi

In [ ]:
# Do przekształcenia array w matrycę wykorzystaj funkcję .reshape()
# Podając jeden z parametrów (dowolny) jako docelowa ilość wierszy/kolumn, a drugi jako -1 mówisz algorytmowi: "Chcę mieć X wierszy/kolumn i wynikową ilość kolumn/wierszy"

##Podpowiedzi + rozwiązanie

In [ ]:
# Do przekształcenia array w matrycę wykorzystaj funkcję .reshape()
# Podając jeden z parametrów (dowolny) jako docelowa ilość wierszy/kolumn, a drugi jako -1 mówisz algorytmowi: "Chcę mieć X wierszy/kolumn i wynikową ilość kolumn/wierszy"

ar4 = np.linspace(20,35,16)
print(ar4.reshape(4,4))
print(ar4.reshape(8,-1))
print(ar4.reshape(-1,8))
print(ar4.reshape(4,5))

[[20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]
 [32. 33. 34. 35.]]
[[20. 21.]
 [22. 23.]
 [24. 25.]
 [26. 27.]
 [28. 29.]
 [30. 31.]
 [32. 33.]
 [34. 35.]]
[[20. 21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34. 35.]]


ValueError: ignored