<a href="https://colab.research.google.com/github/191919201921/Zadania_Domowe_ADS/blob/main/Kopia_notatnika_M5PD1V1_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modul 5 - Praca domowa - Python

Zwykle istnieje wiele sposobów, żeby rozwiązać zadanie w Python. Także czasami warto spróbować opracować kod na 1-2 sposoby :)

## Zadanie - 1

Utwórz macierze a także przeprowadź na nich obliczenia. Postępuj wg. kroków:
* ustaw ziarno losowości równe `5` wykorzystując funkcję dostępną w bibliotece `numpy`;
* wygeneruj 2 ciągi liczb całkowitych z zakresu od 1 do 100. Określ liczbę elementów 20 i 32 odpowiednio. Do tego możesz użyć funkcji: `np.random.randint()`;
* wykorzystaj wygenerowane liczby aby stworzyć macierze `5x4` i `4x8` odpowiednio;
* wykonaj mnożenie stworzonych macierzy;
* podnieś wszystkie elementy macierzy wynikowej z poprzedniego kroku do potęgi `2`;
* odejmij wartość minimalną od każdego elementu macierzy z poprzedniego kroku;
* wylicz sumę wszystkich elementów macierzy;
* podziel się wynikiem w grupie na [FB](https://bit.ly/2OSyHaG) podając hashtag `#modul5zadanie1`.<br>

<img src="https://media.giphy.com/media/quEsMOrr3hmQ8/giphy.gif" weight=400>

In [ ]:
import numpy as np

In [ ]:
np.random.seed(5)

In [ ]:
x = np.random.randint(1,100,20)
y = np.random.randint(1,100,32)

In [ ]:
print(x)
print(y)

[79 62 17 74  9 63 28 31 81  8 77 16 54 81 28 45 78 76 66 48]
[31 85 87 19 10 42 63  2 83 17 79  6 59  1 81  5 37 52 28 32  3 69 39 84
 20 19  8 31 63 12 68 66]


In [ ]:
x.shape

(20,)

In [ ]:
x2 = x.reshape(5,4)
y2= y.reshape(4,8)

In [ ]:
print(x2)
print(y2)

[[79 62 17 74]
 [ 9 63 28 31]
 [81  8 77 16]
 [54 81 28 45]
 [78 76 66 48]]
[[31 85 87 19 10 42 63  2]
 [83 17 79  6 59  1 81  5]
 [37 52 28 32  3 69 39 84]
 [20 19  8 31 63 12 68 66]]


In [ ]:
type(x2)

numpy.ndarray

In [ ]:
np.dot(x2,y2)

array([[ 9704, 10059, 12839,  4711,  9161,  5441, 15694,  6780],
       [ 7164,  3881,  6792,  2406,  5844,  2745,  8870,  4731],
       [ 6344, 11329,  9963,  4547,  2521,  8915,  9842,  7726],
       [10333,  8278, 12241,  3803,  8238,  4821, 14115,  5835],
       [12128, 12266, 15022,  5538,  8486,  8482, 16908,  9248]])

## Zadanie - 2

Wykorzystaj podejście statystyki opisowej do [Zbioru Danych](https://bit.ly/2XXZo2R) o ocenie czerwonego wina aby odpowiedzieć na kolejne pytania:
* jak wyglądają podstawowe statystyki dotyczace zbioru danych?
* jak wygląda rozkład dla poszczególnych kolumn? 
* jakie są średnie charakterystyki najlepszego wina?
* jakie są średnie charakterystyki najgorszego wina?
* czy mocniejsze wino ma lepsze oceny?
* jakie zależności widać w danych?
* jakie cechy w największym stopniu wpływają na ocenę czerwonego wina?


> Dane dotyczące oceny jakości portugalskiego czerwonego wina `Vinho Verde` na podstawie danych z próbek i sensorów. Eksperci oceniali wino w skali od 0 do 10 (bardzo złe i bardzo dobre odpowiednio). [Więcej o danych...](https://bit.ly/2FiwKmy)

<img src="https://media.giphy.com/media/5saWnCIJL7nmU/giphy.gif" width="400">


In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff

In [ ]:
dane = pd.read_csv('/content/red_wine.csv')
dane

Unnamed: 0  fixed.acidity  volatile.acidity  ...  sulphates  alcohol  quality
0              1            7.4             0.700  ...       0.56      9.4        5
1              2            7.8             0.880  ...       0.68      9.8        5
2              3            7.8             0.760  ...       0.65      9.8        5
3              4           11.2             0.280  ...       0.58      9.8        6
4              5            7.4             0.700  ...       0.56      9.4        5
...          ...            ...               ...  ...        ...      ...      ...
1594        1595            6.2             0.600  ...       0.58     10.5        5
1595        1596            5.9             0.550  ...       0.76     11.2        6
1596        1597            6.3             0.510  ...       0.75     11.0        6
1597        1598            5.9             0.645  ...       0.71     10.2        5
1598        1599            6.0             0.310  ...       0.66     11.0        6

[1599 rows x 13 columns]

In [ ]:
dane.describe()

Unnamed: 0  fixed.acidity  ...      alcohol      quality
count  1599.000000    1599.000000  ...  1599.000000  1599.000000
mean    800.000000       8.319637  ...    10.422983     5.636023
std     461.735855       1.741096  ...     1.065668     0.807569
min       1.000000       4.600000  ...     8.400000     3.000000
25%     400.500000       7.100000  ...     9.500000     5.000000
50%     800.000000       7.900000  ...    10.200000     6.000000
75%    1199.500000       9.200000  ...    11.100000     6.000000
max    1599.000000      15.900000  ...    14.900000     8.000000

[8 rows x 13 columns]

In [ ]:
zq = dane['quality']
zbior_quality = np.array(zq)
zbior_quality

array([5, 5, 5, ..., 6, 5, 6])

In [ ]:
ff.create_distplot([zbior_quality],['Quality'])
#XDDD

In [ ]:
najlepsze_wino = dane.sort_values('quality',ascending = False)
najlepsze_wino = najlepsze_wino.head(1)
najlepsze_wino
#bez sensu powyższe. tą samą ocene moze miec kilka win. -> zbadać grupę.

Unnamed: 0  fixed.acidity  volatile.acidity  ...  sulphates  alcohol  quality
495         496           10.7              0.35  ...       0.65     11.0        8

[1 rows x 13 columns]

In [ ]:
najlepsze_wina = dane[dane['quality'] == 8]
najlepsze_wina

Unnamed: 0  fixed.acidity  volatile.acidity  ...  sulphates  alcohol  quality
267          268            7.9              0.35  ...       0.86     12.8        8
278          279           10.3              0.32  ...       0.82     12.6        8
390          391            5.6              0.85  ...       0.82     12.9        8
440          441           12.6              0.31  ...       0.82      9.8        8
455          456           11.3              0.62  ...       0.69     13.4        8
481          482            9.4              0.30  ...       0.92     11.7        8
495          496           10.7              0.35  ...       0.65     11.0        8
498          499           10.7              0.35  ...       0.65     11.0        8
588          589            5.0              0.42  ...       0.74     14.0        8
828          829            7.8              0.57  ...       0.74     12.7        8
1061        1062            9.1              0.40  ...       0.69     12.5        8
1090        1091           10.0              0.26  ...       0.63     11.8        8
1120        1121            7.9              0.54  ...       0.72     13.1        8
1202        1203            8.6              0.42  ...       0.69     11.7        8
1269        1270            5.5              0.49  ...       0.82     14.0        8
1403        1404            7.2              0.33  ...       1.10     10.0        8
1449        1450            7.2              0.38  ...       0.76     11.3        8
1549        1550            7.4              0.36  ...       0.70     11.4        8

[18 rows x 13 columns]

In [ ]:
najlepsze_wina.describe()
#średnie statystyki w wierszu "mean".

Unnamed: 0  fixed.acidity  ...    alcohol  quality
count    18.000000      18.000000  ...  18.000000     18.0
mean    826.722222       8.566667  ...  12.094444      8.0
std     438.922719       2.119656  ...   1.224011      0.0
min     268.000000       5.000000  ...   9.800000      8.0
25%     462.500000       7.250000  ...  11.325000      8.0
50%     709.000000       8.250000  ...  12.150000      8.0
75%    1182.500000      10.225000  ...  12.875000      8.0
max    1550.000000      12.600000  ...  14.000000      8.0

[8 rows x 13 columns]

In [ ]:
najgorsze_wina = dane.sort_values('quality',ascending = False)
najgorsze_wina = najgorsze_wina[najgorsze_wina['quality'] == 3]
najgorsze_wina

Unnamed: 0  fixed.acidity  volatile.acidity  ...  sulphates  alcohol  quality
1469        1470            7.3             0.980  ...       0.55     9.70        3
1374        1375            6.8             0.815  ...       0.51     9.80        3
459          460           11.6             0.580  ...       0.57     9.00        3
1505        1506            6.7             0.760  ...       0.63     9.95        3
517          518           10.4             0.610  ...       0.63     8.40        3
690          691            7.4             1.185  ...       0.54    10.70        3
1478        1479            7.1             0.875  ...       0.52    10.20        3
899          900            8.3             1.020  ...       0.49    11.00        3
1299        1300            7.6             1.580  ...       0.40    10.90        3
832          833           10.4             0.440  ...       0.86     9.90        3

[10 rows x 13 columns]

In [ ]:
najgorsze_wina.describe()
#średnie statystyki najgorszych win w kolumnie "mean".

Unnamed: 0  fixed.acidity  ...    alcohol  quality
count    10.00000      10.000000  ...  10.000000     10.0
mean   1053.20000       8.360000  ...   9.955000      3.0
std     417.13222       1.770875  ...   0.818009      0.0
min     460.00000       6.700000  ...   8.400000      3.0
25%     726.50000       7.150000  ...   9.725000      3.0
50%    1100.00000       7.500000  ...   9.925000      3.0
75%    1446.25000       9.875000  ...  10.575000      3.0
max    1506.00000      11.600000  ...  11.000000      3.0

[8 rows x 13 columns]

In [ ]:
#czy mocniejsze wino ma lepsze oceny niż słabsze?

px.box(dane,
       x = 'quality',
       y = 'alcohol',
       title = 'ocena ze względu na moc wina.')

#na ponizszym wykresie widać, że alkohol z "quality" = 8 ma więcej wyników w wysokoprocentowych winach -> mediana 12.15%, grupa niskoprocentowych jest nieliczna w ocenie 8.

In [ ]:
#czy mocniejsze wino ma lepsze oceny niż słabsze?

px.scatter(dane,
           x = 'quality',
           y= 'alcohol',
           )

#widzimy, że wina powyżej 13%% praktycznie nie występują w jakości poniżej 6.

In [ ]:
korelacja = dane.corr()
korelacja

Unnamed: 0  fixed.acidity  ...   alcohol   quality
Unnamed: 0              1.000000      -0.268484  ...  0.245123  0.066453
fixed.acidity          -0.268484       1.000000  ... -0.061668  0.124052
volatile.acidity       -0.008815      -0.256131  ... -0.202288 -0.390558
citric.acid            -0.153551       0.671703  ...  0.109903  0.226373
residual.sugar         -0.031261       0.114777  ...  0.042075  0.013732
chlorides              -0.119869       0.093705  ... -0.221141 -0.128907
free.sulfur.dioxide     0.090480      -0.153794  ... -0.069408 -0.050656
total.sulfur.dioxide   -0.117850      -0.113181  ... -0.205654 -0.185100
density                -0.368372       0.668047  ... -0.496180 -0.174919
pH                      0.136005      -0.682978  ...  0.205633 -0.057731
sulphates              -0.125307       0.183006  ...  0.093595  0.251397
alcohol                 0.245123      -0.061668  ...  1.000000  0.476166
quality                 0.066453       0.124052  ...  0.476166  1.000000

[13 rows x 13 columns]

In [ ]:
'''
korelacje..

density -> fixed.acidity = 0.66
citric.acid -> fixed.acidity = 0.67
total.sulfur.dioxide -> free.sulfur.dioxide = 0.66 

dodatkowo - > jakość zależy od poziomu alkoholu w 47%

'''
px.imshow(korelacja)


In [ ]:
korelacja['quality'].sort_values()

volatile.acidity       -0.390558
total.sulfur.dioxide   -0.185100
density                -0.174919
chlorides              -0.128907
pH                     -0.057731
free.sulfur.dioxide    -0.050656
residual.sugar          0.013732
Unnamed: 0              0.066453
fixed.acidity           0.124052
citric.acid             0.226373
sulphates               0.251397
alcohol                 0.476166
quality                 1.000000
Name: quality, dtype: float64

In [ ]:
# na ocenę czerwonego wina wpływają najbardziej:
# jakość zależy od poziomu alkoholu 0.47
# fixed.acidity           0.124052
# citric.acid             0.226373
# sulphates               0.251397
# alcohol                 0.476166